trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  SPAUTH_ENV: 'production'
  SPAUTH_FORCE: 'true'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install -g yo
  displayName: 'Global dependencies'

- script: npm install
  displayName: 'Restore dependencies'
  env:
    SNYK_TOKEN: $(ci.snyk.token)

- script: |
    npm run lint
    npm run build
  displayName: 'Lint & Build'

- script: npm run test
  displayName: 'Run tests'
  env:
    SPAUTH_SITEURL: $(ci.spo.siteurl)
    SPAUTH_USERNAME: $(ci.spo.username)
    SPAUTH_PASSWORD: $(ci.spo.password)
  timeoutInMinutes: 15
