// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/yosay/yosay.d.ts
declare module 'yosay' {
  function yosay(message?: string, options?: {maxLength: number}): string;
  export = yosay;
}
